"""Neighborhood alias mapping and tier configuration."""

from models.enums import Borough

# Canonical neighborhood → borough mapping
NEIGHBORHOOD_BOROUGHS: dict[str, Borough] = {
    # Manhattan - Midtown East area
    "Midtown East": Borough.MANHATTAN,
    "Murray Hill": Borough.MANHATTAN,
    "Turtle Bay": Borough.MANHATTAN,
    "Kips Bay": Borough.MANHATTAN,
    "Tudor City": Borough.MANHATTAN,
    "Sutton Place": Borough.MANHATTAN,
    # Manhattan - LES area
    "Lower East Side": Borough.MANHATTAN,
    "East Village": Borough.MANHATTAN,
    "Nolita": Borough.MANHATTAN,
    "Two Bridges": Borough.MANHATTAN,
    "Alphabet City": Borough.MANHATTAN,
    # Manhattan - Other Midtown/Downtown
    "Midtown": Borough.MANHATTAN,
    "Midtown West": Borough.MANHATTAN,
    "Hell's Kitchen": Borough.MANHATTAN,
    "Chelsea": Borough.MANHATTAN,
    "Flatiron": Borough.MANHATTAN,
    "Gramercy": Borough.MANHATTAN,
    "Union Square": Borough.MANHATTAN,
    "NoMad": Borough.MANHATTAN,
    "Hudson Yards": Borough.MANHATTAN,
    "West Village": Borough.MANHATTAN,
    "Greenwich Village": Borough.MANHATTAN,
    "SoHo": Borough.MANHATTAN,
    "NoHo": Borough.MANHATTAN,
    "Tribeca": Borough.MANHATTAN,
    "Financial District": Borough.MANHATTAN,
    "Battery Park City": Borough.MANHATTAN,
    "Chinatown": Borough.MANHATTAN,
    "Little Italy": Borough.MANHATTAN,
    # Manhattan - Uptown
    "Upper East Side": Borough.MANHATTAN,
    "Upper West Side": Borough.MANHATTAN,
    "Yorkville": Borough.MANHATTAN,
    "Lenox Hill": Borough.MANHATTAN,
    "Carnegie Hill": Borough.MANHATTAN,
    "Harlem": Borough.MANHATTAN,
    "East Harlem": Borough.MANHATTAN,
    "Washington Heights": Borough.MANHATTAN,
    "Inwood": Borough.MANHATTAN,
    "Morningside Heights": Borough.MANHATTAN,
    # Brooklyn
    "Williamsburg": Borough.BROOKLYN,
    "DUMBO": Borough.BROOKLYN,
    "Brooklyn Heights": Borough.BROOKLYN,
    "Downtown Brooklyn": Borough.BROOKLYN,
    "Fort Greene": Borough.BROOKLYN,
    "Clinton Hill": Borough.BROOKLYN,
    "Park Slope": Borough.BROOKLYN,
    "Cobble Hill": Borough.BROOKLYN,
    "Boerum Hill": Borough.BROOKLYN,
    "Carroll Gardens": Borough.BROOKLYN,
    "Prospect Heights": Borough.BROOKLYN,
    "Greenpoint": Borough.BROOKLYN,
    "Bushwick": Borough.BROOKLYN,
    "Bed-Stuy": Borough.BROOKLYN,
    "Crown Heights": Borough.BROOKLYN,
    "Sunset Park": Borough.BROOKLYN,
    "Bay Ridge": Borough.BROOKLYN,
    # Queens
    "Long Island City": Borough.QUEENS,
    "Astoria": Borough.QUEENS,
    "Sunnyside": Borough.QUEENS,
    "Jackson Heights": Borough.QUEENS,
    "Flushing": Borough.QUEENS,
    "Forest Hills": Borough.QUEENS,
}

# Common aliases / misspellings → canonical name
NEIGHBORHOOD_ALIASES: dict[str, str] = {
    "les": "Lower East Side",
    "lower east side": "Lower East Side",
    "ues": "Upper East Side",
    "upper east side": "Upper East Side",
    "uws": "Upper West Side",
    "upper west side": "Upper West Side",
    "fidi": "Financial District",
    "financial district": "Financial District",
    "bk heights": "Brooklyn Heights",
    "brooklyn heights": "Brooklyn Heights",
    "wburg": "Williamsburg",
    "williamsburg": "Williamsburg",
    "lic": "Long Island City",
    "long island city": "Long Island City",
    "hells kitchen": "Hell's Kitchen",
    "hell's kitchen": "Hell's Kitchen",
    "nomad": "NoMad",
    "noho": "NoHo",
    "soho": "SoHo",
    "dumbo": "DUMBO",
    "gramercy park": "Gramercy",
    "gramercy": "Gramercy",
    "murray hill": "Murray Hill",
    "midtown east": "Midtown East",
    "midtown west": "Midtown West",
    "grand central": "Midtown East",
    "near grand central": "Midtown East",
    "turtle bay": "Turtle Bay",
    "kips bay": "Kips Bay",
    "tudor city": "Tudor City",
    "sutton place": "Sutton Place",
    "east village": "East Village",
    "west village": "West Village",
    "greenwich village": "Greenwich Village",
    "the village": "Greenwich Village",
    "nolita": "Nolita",
    "two bridges": "Two Bridges",
    "alphabet city": "Alphabet City",
    "midtown": "Midtown",
    "chelsea": "Chelsea",
    "flatiron": "Flatiron",
    "flatiron district": "Flatiron",
    "union square": "Union Square",
    "union sq": "Union Square",
    "hudson yards": "Hudson Yards",
    "tribeca": "Tribeca",
    "battery park": "Battery Park City",
    "battery park city": "Battery Park City",
    "chinatown": "Chinatown",
    "little italy": "Little Italy",
    "yorkville": "Yorkville",
    "lenox hill": "Lenox Hill",
    "carnegie hill": "Carnegie Hill",
    "harlem": "Harlem",
    "east harlem": "East Harlem",
    "washington heights": "Washington Heights",
    "inwood": "Inwood",
    "morningside heights": "Morningside Heights",
    "morningside": "Morningside Heights",
    "fort greene": "Fort Greene",
    "clinton hill": "Clinton Hill",
    "park slope": "Park Slope",
    "cobble hill": "Cobble Hill",
    "boerum hill": "Boerum Hill",
    "carroll gardens": "Carroll Gardens",
    "prospect heights": "Prospect Heights",
    "greenpoint": "Greenpoint",
    "bushwick": "Bushwick",
    "bed-stuy": "Bed-Stuy",
    "bed stuy": "Bed-Stuy",
    "bedford-stuyvesant": "Bed-Stuy",
    "bedford stuyvesant": "Bed-Stuy",
    "crown heights": "Crown Heights",
    "sunset park": "Sunset Park",
    "bay ridge": "Bay Ridge",
    "downtown brooklyn": "Downtown Brooklyn",
    "astoria": "Astoria",
    "sunnyside": "Sunnyside",
    "jackson heights": "Jackson Heights",
    "flushing": "Flushing",
    "forest hills": "Forest Hills",
}


def normalize_neighborhood(raw: str) -> str:
    """Normalize a raw neighborhood string to a canonical name."""
    if not raw:
        return ""
    key = raw.lower().strip()
    return NEIGHBORHOOD_ALIASES.get(key, raw.strip().title())


def get_borough(neighborhood: str) -> Borough:
    """Get the borough for a canonical neighborhood name."""
    return NEIGHBORHOOD_BOROUGHS.get(neighborhood, Borough.UNKNOWN)
